on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 'testing github action'
        run: cd

     - name: 'testing printing'
        run: echo Mohamed
